/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackMyOrderRouteImport } from './routes/track-my-order'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsroomSlugRouteImport } from './routes/newsroom.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedMemberDashboardRouteImport } from './routes/_authenticated/member-dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicRecordSignatureRouteImport } from './routes/api/public/record-signature'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicHooksShopifyOrdersRouteImport } from './routes/api/public/hooks/shopify-orders'
import { Route as ApiPublicHooksScrapeArticlesRouteImport } from './routes/api/public/hooks/scrape-articles'

const TrackMyOrderRoute = TrackMyOrderRouteImport.update({
  id: '/track-my-order',
  path: '/track-my-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomSlugRoute = NewsroomSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsroomRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemberDashboardRoute =
  AuthenticatedMemberDashboardRouteImport.update({
    id: '/member-dashboard',
    path: '/member-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRecordSignatureRoute =
  ApiPublicRecordSignatureRouteImport.update({
    id: '/api/public/record-signature',
    path: '/api/public/record-signature',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShopifyOrdersRoute =
  ApiPublicHooksShopifyOrdersRouteImport.update({
    id: '/api/public/hooks/shopify-orders',
    path: '/api/public/hooks/shopify-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScrapeArticlesRoute =
  ApiPublicHooksScrapeArticlesRouteImport.update({
    id: '/api/public/hooks/scrape-articles',
    path: '/api/public/hooks/scrape-articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/launch': typeof LaunchRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/newsroom': typeof NewsroomRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/referrals': typeof ReferralsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-my-order': typeof TrackMyOrderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/member-dashboard': typeof AuthenticatedMemberDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/newsroom/$slug': typeof NewsroomSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/record-signature': typeof ApiPublicRecordSignatureRoute
  '/api/public/hooks/scrape-articles': typeof ApiPublicHooksScrapeArticlesRoute
  '/api/public/hooks/shopify-orders': typeof ApiPublicHooksShopifyOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/launch': typeof LaunchRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/newsroom': typeof NewsroomRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/referrals': typeof ReferralsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-my-order': typeof TrackMyOrderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/member-dashboard': typeof AuthenticatedMemberDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/newsroom/$slug': typeof NewsroomSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/record-signature': typeof ApiPublicRecordSignatureRoute
  '/api/public/hooks/scrape-articles': typeof ApiPublicHooksScrapeArticlesRoute
  '/api/public/hooks/shopify-orders': typeof ApiPublicHooksShopifyOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/launch': typeof LaunchRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/newsroom': typeof NewsroomRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/referrals': typeof ReferralsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-my-order': typeof TrackMyOrderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/member-dashboard': typeof AuthenticatedMemberDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/newsroom/$slug': typeof NewsroomSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/record-signature': typeof ApiPublicRecordSignatureRoute
  '/api/public/hooks/scrape-articles': typeof ApiPublicHooksScrapeArticlesRoute
  '/api/public/hooks/shopify-orders': typeof ApiPublicHooksShopifyOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/contact'
    | '/launch'
    | '/mcp'
    | '/membership'
    | '/newsroom'
    | '/privacy-policy'
    | '/referrals'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/track-my-order'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/member-dashboard'
    | '/api/chat'
    | '/newsroom/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/record-signature'
    | '/api/public/hooks/scrape-articles'
    | '/api/public/hooks/shopify-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/contact'
    | '/launch'
    | '/mcp'
    | '/membership'
    | '/newsroom'
    | '/privacy-policy'
    | '/referrals'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/track-my-order'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/member-dashboard'
    | '/api/chat'
    | '/newsroom/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/record-signature'
    | '/api/public/hooks/scrape-articles'
    | '/api/public/hooks/shopify-orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community-guidelines'
    | '/contact'
    | '/launch'
    | '/mcp'
    | '/membership'
    | '/newsroom'
    | '/privacy-policy'
    | '/referrals'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/track-my-order'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/member-dashboard'
    | '/api/chat'
    | '/newsroom/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/record-signature'
    | '/api/public/hooks/scrape-articles'
    | '/api/public/hooks/shopify-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  LaunchRoute: typeof LaunchRoute
  McpRoute: typeof McpRoute
  MembershipRoute: typeof MembershipRoute
  NewsroomRoute: typeof NewsroomRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReferralsRoute: typeof ReferralsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackMyOrderRoute: typeof TrackMyOrderRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicRecordSignatureRoute: typeof ApiPublicRecordSignatureRoute
  ApiPublicHooksScrapeArticlesRoute: typeof ApiPublicHooksScrapeArticlesRoute
  ApiPublicHooksShopifyOrdersRoute: typeof ApiPublicHooksShopifyOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-my-order': {
      id: '/track-my-order'
      path: '/track-my-order'
      fullPath: '/track-my-order'
      preLoaderRoute: typeof TrackMyOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom/$slug': {
      id: '/newsroom/$slug'
      path: '/$slug'
      fullPath: '/newsroom/$slug'
      preLoaderRoute: typeof NewsroomSlugRouteImport
      parentRoute: typeof NewsroomRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/member-dashboard': {
      id: '/_authenticated/member-dashboard'
      path: '/member-dashboard'
      fullPath: '/member-dashboard'
      preLoaderRoute: typeof AuthenticatedMemberDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/record-signature': {
      id: '/api/public/record-signature'
      path: '/api/public/record-signature'
      fullPath: '/api/public/record-signature'
      preLoaderRoute: typeof ApiPublicRecordSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shopify-orders': {
      id: '/api/public/hooks/shopify-orders'
      path: '/api/public/hooks/shopify-orders'
      fullPath: '/api/public/hooks/shopify-orders'
      preLoaderRoute: typeof ApiPublicHooksShopifyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-articles': {
      id: '/api/public/hooks/scrape-articles'
      path: '/api/public/hooks/scrape-articles'
      fullPath: '/api/public/hooks/scrape-articles'
      preLoaderRoute: typeof ApiPublicHooksScrapeArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMemberDashboardRoute: typeof AuthenticatedMemberDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMemberDashboardRoute: AuthenticatedMemberDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NewsroomRouteChildren {
  NewsroomSlugRoute: typeof NewsroomSlugRoute
}

const NewsroomRouteChildren: NewsroomRouteChildren = {
  NewsroomSlugRoute: NewsroomSlugRoute,
}

const NewsroomRouteWithChildren = NewsroomRoute._addFileChildren(
  NewsroomRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  LaunchRoute: LaunchRoute,
  McpRoute: McpRoute,
  MembershipRoute: MembershipRoute,
  NewsroomRoute: NewsroomRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReferralsRoute: ReferralsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackMyOrderRoute: TrackMyOrderRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicRecordSignatureRoute: ApiPublicRecordSignatureRoute,
  ApiPublicHooksScrapeArticlesRoute: ApiPublicHooksScrapeArticlesRoute,
  ApiPublicHooksShopifyOrdersRoute: ApiPublicHooksShopifyOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
